### ISSUE TITLE
module omitted in doc ?

### ISSUE THREAD

**Issue by AndKe** [lephisto/tesla-apiscraper#24]
```
andre@ODIN:~/tesla-apiscraper$ python ./apiscraper.py 
Traceback (most recent call last):
  File "./apiscraper.py", line 33, in <module>
    from srtmread import elevationtoinflux
  File "/home/andre/tesla-apiscraper/srtmread.py", line 4, in <module>
    from pathlib import Path
ImportError: No module named pathlib

```

**Comment by lephisto** [comment]
Maybe, thanks for pointing out. On Ubuntu this seems to be default.

Retrofit with "apt install python-pathlib" or "pip install pathlib". 

I will adjust the Doc.
