### ISSUE TITLE
Sleep prevented by small value changes

### ISSUE THREAD

**Issue by markusdd** [lephisto/tesla-apiscraper#27]
Hi,

on some days this does not seem to happen, but especially when there are changing weather conditions small changes in ambient temperature and battery range will keep the car permanently awake.

Here is an example form my logs: 
2019-03-17 22:34:09 INFO     >> self.connection.refresh_vehicle()
[httpd] 127.0.0.1 - tesla [17/Mar/2019:22:34:10 +0000] "POST /write?db=tesla HTTP/1.1" 204 0 "-" "python-requests/2.21.0" c8b7e87f-4904-11e9-8210-0242ac110004 5012
2019-03-17 22:34:10 INFO     Car State: online Poll Interval: 512
2019-03-17 22:34:10 INFO     >> Request vehicle data
2019-03-17 22:34:14 INFO     Value Change, SG: charge_state: Logging...battery_range: old value: 241.21, new value: 241.19
[httpd] 127.0.0.1 - tesla [17/Mar/2019:22:34:14 +0000] "POST /write?db=tesla HTTP/1.1" 204 0 "-" "python-requests/2.21.0" cb3a48ef-4904-11e9-8211-0242ac110004 6944
2019-03-17 22:34:14 INFO     Value Change, SG: charge_state: Logging...est_battery_range: old value: 127.32, new value: 127.31
[httpd] 127.0.0.1 - tesla [17/Mar/2019:22:34:14 +0000] "POST /write?db=tesla HTTP/1.1" 204 0 "-" "python-requests/2.21.0" cb3cc795-4904-11e9-8212-0242ac110004 5718
2019-03-17 22:34:15 INFO     Value Change, SG: charge_state: Logging...ideal_battery_range: old value: 192.97, new value: 192.95
[httpd] 127.0.0.1 - tesla [17/Mar/2019:22:34:15 +0000] "POST /write?db=tesla HTTP/1.1" 204 0 "-" "python-requests/2.21.0" cb3f1b25-4904-11e9-8213-0242ac110004 5840
2019-03-17 22:34:15 INFO     Value Change, SG: climate_state: Logging...inside_temp: old value: 12.5, new value: 12.2
[httpd] 127.0.0.1 - tesla [17/Mar/2019:22:34:15 +0000] "POST /write?db=tesla HTTP/1.1" 204 0 "-" "python-requests/2.21.0" cb419647-4904-11e9-8214-0242ac110004 6018
2019-03-17 22:34:15 INFO     Asleep since: 1552628220.7 Sleeping for 256 seconds..

Somehow the poll interval is already extended, but it does never seem to reach the 'sleep' length.
I checked Grafana and the car was online the whole day although it was not moved for 1.5 days.

Would it make sense to round to whole numbers when checking to avoid this wakelock?
As mentioned, on days which are relatively 'homogenous' from a weather perpective this does not seem to happen. Today was a wild mixture of wind, rain and sun, and the car never went to sleep.

**Comment by markusdd** [comment]
Just noticed in the project network that at least for temperature someone has already considered this:
(bit convoluted because first version had 1 Typo and missing conversion)

https://github.com/dpilone/tesla-apiscraper/commit/a277a9fa2be31fdb2041a0c419c38048853d1953
https://github.com/dpilone/tesla-apiscraper/commit/719f8c9ba2003eb0db9d8750df7fe84c575f01d5
https://github.com/dpilone/tesla-apiscraper/commit/0e283b7a62a439bbcb926f997bf46667cc505154

**Comment by ahornerr** [comment]
I tried the fork at https://github.com/dpilone/tesla-apiscraper and received the following stacktrace:

```python
...
2019-03-18 22:33:28 INFO     Value Change, SG: climate_state: Logging...max_avail_temp: old value: , new value: 28.0
2019-03-18 22:33:28 INFO     Value Change, SG: climate_state: Logging...min_avail_temp: old value: , new value: 15.0
Traceback (most recent call last):
  File "/tesla-apiscraper/apiscraper.py", line 464, in <module>
    poll_interval = state_monitor.check_states(poll_interval)
  File "/tesla-apiscraper/apiscraper.py", line 245, in check_states
    if self.request_state_group():
  File "/tesla-apiscraper/apiscraper.py", line 199, in request_state_group
    new_value = round(float(new_value));
TypeError: float() argument must be a string or a number
```

**Comment by markusdd** [comment]
That is absolutely possible, I pointed to these commits more as an idea on how to maybe handle the problem. I already observed it's not fit for a merge request (and also not done by me, just found it by accident)

**Comment by ahornerr** [comment]
After doing some debugging it appears that `new_value` can be `None`. Simple fix of changing line 198 to
```python
if (new_value is not None) and ((element == "inside_temp") or (element == "outside_temp")):
```

appears to fix the issue!

**Comment by markusdd** [comment]
This is not enough, as the old_value can also be an empty string I discovered.
Also it is advisable to add "charge_port_latch" to the ignore list as this sometimes seems to deliver the value 'invalid' before returning to 'Blocking', which also can create a wakelock.

**Comment by markusdd** [comment]
I built a merge request:
https://github.com/lephisto/tesla-apiscraper/pull/28

**Comment by lephisto** [comment]
I will test it those days and give it a rls tag if all fine. Thank you!

**Comment by markusdd** [comment]
Thanks for merging!
Did a bit testing the last 2 days and with the range and temperature being handled this way and with excluding the charge port latch parameter, I got reliable sleep within 20-30min of parking the car.

If certain people would like that we could think about making the 'tolerance values' adjustable, but I think half a km of range and rounding to full degrees is very acceptable.

**Comment by trixing** [comment]
Here are a few more slowly changing values, which prevent my car from sleeping.

charger_voltage < 10 can probably be safely ignored (it is not connected) and the range values could be rounded to full kms.

2019-04-06 14:52:11 INFO     Value Change, SG: charge_state: Logging...battery_range: old value: 138.98, new value: 138.15
INFO:apiscraper:Value Change, SG: charge_state: Logging...battery_range: old value: 138.98, new value: 138.15
2019-04-06 14:52:11 INFO     Value Change, SG: charge_state: Logging...charger_voltage: old value: 2, new value: 1
INFO:apiscraper:Value Change, SG: charge_state: Logging...charger_voltage: old value: 2, new value: 1
2019-04-06 14:52:11 INFO     Value Change, SG: charge_state: Logging...est_battery_range: old value: 136.45, new value: 135.63
INFO:apiscraper:Value Change, SG: charge_state: Logging...est_battery_range: old value: 136.45, new value: 135.63
2019-04-06 14:52:11 INFO     Value Change, SG: charge_state: Logging...ideal_battery_range: old value: 138.98, new value: 138.15
INFO:apiscraper:Value Change, SG: charge_state: Logging...ideal_battery_range: old value: 138.98, new value: 138.15

**Comment by picard001** [comment]
Same issue here... Maybe it's caused by the the 2019.8 update?  Car won't seem to sleep due to small value changes.

2019-04-05 22:39:56 INFO >> Request vehicle data
2019-04-05 22:39:56 INFO Value Change, SG: charge_state: Logging...battery_range: old value: 261.73, new value: 262.08
2019-04-05 22:39:56 INFO Value Change, SG: charge_state: Logging...charge_energy_added: old value: 1.24, new value: 1.32
2019-04-05 22:39:56 INFO Value Change, SG: charge_state: Logging...est_battery_range: old value: 247.12, new value: 247.45
2019-04-05 22:39:56 INFO Value Change, SG: charge_state: Logging...ideal_battery_range: old value: 261.73, new value: 262.08
2019-04-05 22:39:56 INFO Asleep since: 0 Sleeping for 1 seconds..

**Comment by markusdd** [comment]
Hi, the range values are already also part of my merge-request, so these will be ignored as well when teyh are below 0.5km/mi change.

**Comment by picard001** [comment]
I'm new to github... is there a way to see this merge request so I can test?

**Comment by lephisto** [comment]
This is already part of the current master.
